import type { PreludeTexts } from './prelude';

export const preludeTexts: PreludeTexts = {
    'hd': { description: 'Retorna el primer elemento (cabeza) de una lista no vacía.' },
    'tl': { description: 'Retorna la lista sin su primer elemento (cola).' },
    '#': { description: 'Operador de longitud: cantidad de elementos de la lista (no hay función `length` en el stdenv; se usa `#`).' },
    'reverse': { description: 'Retorna la lista con los elementos en orden inverso.' },
    'concat': { description: 'Concatena una lista de listas en una sola lista.' },
    'map': { description: 'Aplica una función a cada elemento de la lista y retorna la lista de resultados.' },
    'filter': { description: 'Retorna los elementos de la lista que satisfacen el predicado.' },
    'foldl': { description: 'Pliegue por la izquierda con valor inicial.' },
    'foldr': { description: 'Pliegue por la derecha con valor inicial.' },
    'foldl1': { description: 'Pliegue por la izquierda sin valor inicial; usa el primer elemento.' },
    'foldr1': { description: 'Pliegue por la derecha sin valor inicial; usa el último elemento.' },
    'scan': { description: 'Aplica `foldl op r` a cada segmento inicial de la lista y devuelve la lista de acumulados (similar a `scanl` de Haskell).' },
    'take': { description: 'Retorna los primeros `n` elementos de la lista.' },
    'drop': { description: 'Descarta los primeros `n` elementos de la lista.' },
    'takewhile': { description: 'Toma elementos del frente mientras el predicado se cumpla.' },
    'dropwhile': { description: 'Descarta elementos del frente mientras el predicado se cumpla.' },
    'zip2': { description: 'Forma pares con los elementos en la misma posición; la longitud del resultado es la de la lista más corta (estilo habitual en Miranda).' },
    'zip': { description: 'Versión Bird & Wadler: toma un **par** de listas (no currificada). Equivale a `zip2` aplicada a las dos listas.' },
    'map2': { description: 'Recorre dos listas en paralelo aplicando una función binaria (en Haskell suele llamarse `zipWith`).' },
    'zip3': { description: 'Como `zip2` pero con tres listas y ternas.' },
    'zip4': { description: 'Cuatro listas en paralelo → lista de 4-tuplas.' },
    'zip5': { description: 'Cinco listas en paralelo → lista de 5-tuplas.' },
    'zip6': { description: 'Seis listas en paralelo → lista de 6-tuplas (no hay `zip7` en el stdenv).' },
    'transpose': { description: 'Traspone una matriz representada como lista de filas (maneja filas de distinta longitud).' },
    'iterate': { description: 'Genera la lista infinita `[x, f x, f(f x), ...]`.' },
    'repeat': { description: 'Genera la lista infinita con el valor repetido indefinidamente.' },
    'rep': { description: 'Lista finita con `n` copias del mismo valor (replicar; `take n (repeat x)`).' },
    'postfix': { description: 'Añade un elemento al **final** de la lista (dual del constructor `:`).' },
    'member': { description: 'Retorna `True` si el elemento pertenece a la lista.' },
    'index': { description: 'Retorna la lista de índices válidos `[0 .. #x-1]` en orden creciente (p. ej. subscripts legales). No busca un elemento.' },
    'mkset': { description: 'Elimina duplicados conservando el primer encuentro (lista como “conjunto”; en Haskell suele llamarse `nub`).' },
    'sort': { description: 'Ordena la lista en orden ascendente.' },
    'merge': { description: 'Combina dos listas ordenadas en una lista ordenada.' },
    'last': { description: 'Retorna el último elemento de una lista no vacía.' },
    'init': { description: 'Retorna todos los elementos excepto el último.' },
    'sum': { description: 'Suma todos los elementos de la lista.' },
    'product': { description: 'Multiplica todos los elementos de la lista.' },
    'max': { description: 'Mayor elemento de una lista no vacía según el orden `>`.' },
    'min': { description: 'Menor elemento de una lista no vacía según el orden `<`.' },
    'and': { description: 'Retorna `True` si todos los elementos son `True`.' },
    'or': { description: 'Retorna `True` si al menos un elemento es `True`.' },
    'abs': { description: 'Valor absoluto de un número.' },
    'max2': { description: 'Mayor de dos valores según `>=` (el `max` de listas se define con `foldl1 max2`).' },
    'min2': { description: 'Menor de dos valores según `<` (el `min` de listas usa `foldl1 min2`).' },
    'gcd': { description: 'Máximo común divisor de dos enteros.' },
    'neg': { description: 'Negación unaria (equivalente al prefijo `-`).' },
    'subtract': { description: '`subtract x y = y - x` (sección postfija de `-` no permitida en Miranda).' },
    'lcm': { description: 'Mínimo común múltiplo de dos enteros.' },
    'even': { description: 'Retorna `True` si el número es par.' },
    'odd': { description: 'Retorna `True` si el número es impar.' },
    'integer': { description: 'Retorna `True` si el número es un valor entero (sin parte fraccionaria).' },
    'entier': { description: 'Retorna el piso (floor) de un número como entero.' },
    'sqrt': { description: 'Raíz cuadrada.' },
    'exp': { description: 'Función exponencial e^x.' },
    'e': { description: 'Base de los logaritmos naturales (`e = exp 1`).' },
    'log': { description: 'Logaritmo natural (base e).' },
    'log10': { description: 'Logaritmo en base 10.' },
    'sin': { description: 'Seno (argumento en radianes).' },
    'cos': { description: 'Coseno (argumento en radianes).' },
    'tan': { description: 'Tangente (argumento en radianes).' },
    'arctan': { description: 'Arcotangente; resultado en (-π/2, π/2). Ver también `sin`, `cos`.' },
    'pi': { description: 'La constante π ≈ 3.14159265...' },
    'hugenum': { description: 'Mayor número fraccionario representable (orden ~1e308 en IEEE64).' },
    'tinynum': { description: 'Menor positivo distinto de cero representable como fraccionario.' },
    'code': { description: 'Retorna el código ASCII del carácter.' },
    'decode': { description: 'Retorna el carácter correspondiente al código ASCII.' },
    'digit': { description: 'Retorna `True` si el carácter es un dígito decimal.' },
    'letter': { description: 'Retorna `True` si el carácter es una letra.' },
    'spaces': { description: 'Genera una cadena de `n` espacios.' },
    'lay': { description: 'Concatena cadenas añadiendo `\\\\n` al final de cada una (formateo de salida; inverso de `lines` salvo un `\\\\n` final).' },
    'layn': { description: 'Une una lista de cadenas numerando cada línea.' },
    'lines': { description: 'Divide una cadena en una lista de líneas separadas por `\\\\n`.' },
    'cjustify': { description: 'Centra la cadena en un campo de ancho `n` (relleno con espacios).' },
    'ljustify': { description: 'Alinea la cadena a la izquierda en un campo de ancho `n`.' },
    'rjustify': { description: 'Alinea la cadena a la derecha en un campo de ancho `n` (usa `spaces`).' },
    'numval': { description: 'Convierte una cadena a su valor numérico.' },
    'shownum': { description: 'Convierte un número a su representación en cadena.' },
    'showfloat': { description: 'Primer argumento: decimales tras el punto; segundo: el número, en formato fijo.' },
    'showscaled': { description: 'Notación científica; el `num` entero indica decimales en la mantisa.' },
    'show': { description: 'En Miranda, `show` es una **palabra reservada** que denota una familia de conversiones a texto (según el tipo). `shownum` es el caso para `num`.' },
    'id': { description: 'Función identidad: retorna su argumento sin modificarlo.' },
    'const': { description: 'Retorna una función que ignora su argumento y siempre retorna el primer valor.' },
    'converse': { description: 'Intercambia el orden de los dos primeros argumentos de una función binaria currificada.' },
    'until': { description: 'Aplica la función repetidamente hasta que el predicado sea `True`.' },
    'limit': { description: 'Primer valor de la lista igual a su sucesor (convergencia de sucesiones).' },
    'seq': { description: 'Evalúa el primer argumento hasta saber que no es totalmente indefinido y devuelve el segundo.' },
    'force': { description: 'Fuerza evaluación completa de una estructura finita antes de devolverla.' },
    'undef': { description: 'Valor totalmente indefinido; cualquier uso provoca error.' },
    'error': { description: 'Termina el programa con el mensaje de error indicado.' },
    'read': { description: 'Lee el contenido del archivo dado por ruta; error si no existe o no hay permiso.' },
    'filemode': { description: 'Permisos del archivo como cadena tipo `"drwx"` (carácter `-` si no aplica).' },
    'getenv': { description: 'Consulta una variable de entorno por nombre.' },
    'system': { description: 'Ejecuta un comando shell; retorna salida estándar, salida de error y código de salida.' },
    'fst': { description: 'Retorna el primer componente de un par.' },
    'snd': { description: 'Retorna el segundo componente de un par.' },
};
