import type { PreludeTexts } from './prelude';

export const preludeTexts: PreludeTexts = {
    'hd': { description: 'Returns the first element (head) of a non-empty list.' },
    'tl': { description: 'Returns the list without its first element (tail).' },
    '#': { description: 'Length operator: number of elements in the list (there is no `length` in stdenv; use `#`).' },
    'reverse': { description: 'Returns the list with elements in reverse order.' },
    'concat': { description: 'Concatenates a list of lists into a single list.' },
    'map': { description: 'Applies a function to each list element and returns the list of results.' },
    'filter': { description: 'Returns list elements that satisfy the predicate.' },
    'foldl': { description: 'Left fold with an initial value.' },
    'foldr': { description: 'Right fold with an initial value.' },
    'foldl1': { description: 'Left fold without an initial value; uses the first element.' },
    'foldr1': { description: 'Right fold without an initial value; uses the last element.' },
    'scan': { description: 'Applies `foldl op r` to each initial segment and returns the list of accumulators (similar to Haskell `scanl`).' },
    'take': { description: 'Returns the first `n` elements of the list.' },
    'drop': { description: 'Discards the first `n` elements of the list.' },
    'takewhile': { description: 'Takes elements from the front while the predicate holds.' },
    'dropwhile': { description: 'Drops elements from the front while the predicate holds.' },
    'zip2': { description: 'Pairs elements at the same position; result length is that of the shorter list (usual Miranda style).' },
    'zip': { description: 'Bird & Wadler version: takes a **pair** of lists (not curried). Equivalent to `zip2` applied to both lists.' },
    'map2': { description: 'Traverses two lists in parallel applying a binary function (Haskell\'s `zipWith`).' },
    'zip3': { description: 'Like `zip2` but with three lists, producing triples.' },
    'zip4': { description: 'Four lists in parallel → list of 4-tuples.' },
    'zip5': { description: 'Five lists in parallel → list of 5-tuples.' },
    'zip6': { description: 'Six lists in parallel → list of 6-tuples (no `zip7` in stdenv).' },
    'transpose': { description: 'Transposes a matrix represented as a list of rows (handles rows of different lengths).' },
    'iterate': { description: 'Generates the infinite list `[x, f x, f(f x), ...]`.' },
    'repeat': { description: 'Generates the infinite list repeating the value indefinitely.' },
    'rep': { description: 'Finite list of `n` copies of the same value (replicate; `take n (repeat x)`).' },
    'postfix': { description: 'Appends an element to the **end** of the list (dual of the `:` constructor).' },
    'member': { description: 'Returns `True` if the element belongs to the list.' },
    'index': { description: 'Returns the list of valid indices `[0 .. #x-1]` in ascending order (e.g. legal subscripts). Does not search for an element.' },
    'mkset': { description: 'Removes duplicates keeping the first occurrence (list as a set; Haskell\'s `nub`).' },
    'sort': { description: 'Sorts the list in ascending order.' },
    'merge': { description: 'Merges two sorted lists into one sorted list.' },
    'last': { description: 'Returns the last element of a non-empty list.' },
    'init': { description: 'Returns all elements except the last.' },
    'sum': { description: 'Sums all elements of the list.' },
    'product': { description: 'Multiplies all elements of the list.' },
    'max': { description: 'Greatest element of a non-empty list according to `>`.' },
    'min': { description: 'Least element of a non-empty list according to `<`.' },
    'and': { description: 'Returns `True` if all elements are `True`.' },
    'or': { description: 'Returns `True` if at least one element is `True`.' },
    'abs': { description: 'Absolute value of a number.' },
    'max2': { description: 'Greater of two values according to `>=` (list `max` is defined with `foldl1 max2`).' },
    'min2': { description: 'Lesser of two values according to `<` (list `min` uses `foldl1 min2`).' },
    'gcd': { description: 'Greatest common divisor of two integers.' },
    'neg': { description: 'Unary negation (equivalent to prefix `-`).' },
    'subtract': { description: '`subtract x y = y - x` (postfix section of `-` not allowed in Miranda).' },
    'lcm': { description: 'Least common multiple of two integers.' },
    'even': { description: 'Returns `True` if the number is even.' },
    'odd': { description: 'Returns `True` if the number is odd.' },
    'integer': { description: 'Returns `True` if the number is an integer value (no fractional part).' },
    'entier': { description: 'Returns the floor of a number as an integer.' },
    'sqrt': { description: 'Square root.' },
    'exp': { description: 'Exponential function e^x.' },
    'e': { description: 'Base of natural logarithms (`e = exp 1`).' },
    'log': { description: 'Natural logarithm (base e).' },
    'log10': { description: 'Base-10 logarithm.' },
    'sin': { description: 'Sine (argument in radians).' },
    'cos': { description: 'Cosine (argument in radians).' },
    'tan': { description: 'Tangent (argument in radians).' },
    'arctan': { description: 'Arctangent; result in (-π/2, π/2). See also `sin`, `cos`.' },
    'pi': { description: 'The constant π ≈ 3.14159265...' },
    'hugenum': { description: 'Largest representable fractional number (order ~1e308 in IEEE64).' },
    'tinynum': { description: 'Smallest positive non-zero representable fractional number.' },
    'code': { description: 'Returns the ASCII code of the character.' },
    'decode': { description: 'Returns the character for the given ASCII code.' },
    'digit': { description: 'Returns `True` if the character is a decimal digit.' },
    'letter': { description: 'Returns `True` if the character is a letter.' },
    'spaces': { description: 'Generates a string of `n` spaces.' },
    'lay': { description: 'Concatenates strings appending `\\n` after each (output formatting; inverse of `lines` except for a final `\\n`).' },
    'layn': { description: 'Joins a list of strings numbering each line.' },
    'lines': { description: 'Splits a string into a list of lines separated by `\\n`.' },
    'cjustify': { description: 'Centers the string in a field of width `n` (padded with spaces).' },
    'ljustify': { description: 'Left-aligns the string in a field of width `n`.' },
    'rjustify': { description: 'Right-aligns the string in a field of width `n` (uses `spaces`).' },
    'numval': { description: 'Converts a string to its numeric value.' },
    'shownum': { description: 'Converts a number to its string representation.' },
    'showfloat': { description: 'First argument: digits after the decimal point; second: the number, in fixed format.' },
    'showscaled': { description: 'Scientific notation; the integer `num` gives decimal places in the mantissa.' },
    'show': { description: 'In Miranda, `show` is a **reserved word** denoting a family of text conversions (by type). `shownum` is the case for `num`.' },
    'id': { description: 'Identity function: returns its argument unchanged.' },
    'const': { description: 'Returns a function that ignores its argument and always returns the first value.' },
    'converse': { description: 'Swaps the order of the first two arguments of a curried binary function.' },
    'until': { description: 'Applies the function repeatedly until the predicate is `True`.' },
    'limit': { description: 'First value in the list equal to its successor (sequence convergence).' },
    'seq': { description: 'Evaluates the first argument until known not to be fully undefined, then returns the second.' },
    'force': { description: 'Forces full evaluation of a finite structure before returning it.' },
    'undef': { description: 'Fully undefined value; any use causes an error.' },
    'error': { description: 'Terminates the program with the given error message.' },
    'read': { description: 'Reads the contents of the file at the given path; error if missing or no permission.' },
    'filemode': { description: 'File permissions as a string like `"drwx"` (character `-` when not applicable).' },
    'getenv': { description: 'Looks up an environment variable by name.' },
    'system': { description: 'Executes a shell command; returns stdout, stderr, and exit code.' },
    'fst': { description: 'Returns the first component of a pair.' },
    'snd': { description: 'Returns the second component of a pair.' },
};
