export interface PreludeEntry {
    name: string;
    signature: string;
    description: string;
    category: string;
    examples?: string[];
}

export const prelude: PreludeEntry[] = [
    // ── Listas ──────────────────────────────────────────────────────────────
    {
        name: 'hd',
        signature: 'hd :: [*] -> *',
        description: 'Retorna el primer elemento (cabeza) de una lista no vacía.',
        category: 'Listas',
        examples: ['hd [1,2,3]  ||  1', 'hd "abc"    ||  \'a\''],
    },
    {
        name: 'tl',
        signature: 'tl :: [*] -> [*]',
        description: 'Retorna la lista sin su primer elemento (cola).',
        category: 'Listas',
        examples: ['tl [1,2,3]  ||  [2,3]', 'tl "abc"    ||  "bc"'],
    },
    {
        name: '#',
        signature: '# :: [*] -> num',
        description:
            'Operador de longitud: cantidad de elementos de la lista (no hay función `length` en el stdenv; se usa `#`).',
        category: 'Listas',
        examples: ['# [1,2,3]  ||  3', '# []       ||  0', '# "abc"    ||  3'],
    },
    {
        name: 'reverse',
        signature: 'reverse :: [*] -> [*]',
        description: 'Retorna la lista con los elementos en orden inverso.',
        category: 'Listas',
        examples: ['reverse [1,2,3]  ||  [3,2,1]'],
    },
    {
        name: 'concat',
        signature: 'concat :: [[*]] -> [*]',
        description: 'Concatena una lista de listas en una sola lista.',
        category: 'Listas',
        examples: ['concat [[1,2],[3],[4,5]]  ||  [1,2,3,4,5]'],
    },
    {
        name: 'map',
        signature: 'map :: (* -> **) -> [*] -> [**]',
        description: 'Aplica una función a cada elemento de la lista y retorna la lista de resultados.',
        category: 'Listas',
        examples: ['map (*2) [1,2,3]  ||  [2,4,6]', 'map hd [[1,2],[3,4]]  ||  [1,3]'],
    },
    {
        name: 'filter',
        signature: 'filter :: (* -> bool) -> [*] -> [*]',
        description: 'Retorna los elementos de la lista que satisfacen el predicado.',
        category: 'Listas',
        examples: ['filter even [1..6]  ||  [2,4,6]', 'filter (>3) [1..5]  ||  [4,5]'],
    },
    {
        name: 'foldl',
        signature: 'foldl :: (** -> * -> **) -> ** -> [*] -> **',
        description: 'Pliegue por la izquierda con valor inicial.',
        category: 'Listas',
        examples: ['foldl (+) 0 [1,2,3]  ||  6', 'foldl (-) 10 [1,2,3]  ||  4'],
    },
    {
        name: 'foldr',
        signature: 'foldr :: (* -> ** -> **) -> ** -> [*] -> **',
        description: 'Pliegue por la derecha con valor inicial.',
        category: 'Listas',
        examples: ['foldr (+) 0 [1,2,3]  ||  6', 'foldr (:) [] [1,2,3]  ||  [1,2,3]'],
    },
    {
        name: 'foldl1',
        signature: 'foldl1 :: (* -> * -> *) -> [*] -> *',
        description: 'Pliegue por la izquierda sin valor inicial; usa el primer elemento.',
        category: 'Listas',
        examples: ['foldl1 (+) [1,2,3]  ||  6', 'foldl1 max [3,1,4,1,5]  ||  5'],
    },
    {
        name: 'foldr1',
        signature: 'foldr1 :: (* -> * -> *) -> [*] -> *',
        description: 'Pliegue por la derecha sin valor inicial; usa el último elemento.',
        category: 'Listas',
        examples: ['foldr1 (+) [1,2,3]  ||  6'],
    },
    {
        name: 'scan',
        signature: 'scan :: (* -> ** -> *) -> * -> [**] -> [*]',
        description:
            'Aplica `foldl op r` a cada segmento inicial de la lista y devuelve la lista de acumulados (similar a `scanl` de Haskell).',
        category: 'Listas',
        examples: ['scan (+) 0 [1,2,3]  ||  [0,1,3,6]'],
    },
    {
        name: 'take',
        signature: 'take :: num -> [*] -> [*]',
        description: 'Retorna los primeros `n` elementos de la lista.',
        category: 'Listas',
        examples: ['take 3 [1..10]  ||  [1,2,3]', 'take 0 [1,2]    ||  []'],
    },
    {
        name: 'drop',
        signature: 'drop :: num -> [*] -> [*]',
        description: 'Descarta los primeros `n` elementos de la lista.',
        category: 'Listas',
        examples: ['drop 3 [1..5]  ||  [4,5]', 'drop 0 [1,2]   ||  [1,2]'],
    },
    {
        name: 'takewhile',
        signature: 'takewhile :: (* -> bool) -> [*] -> [*]',
        description: 'Toma elementos del frente mientras el predicado se cumpla.',
        category: 'Listas',
        examples: ['takewhile even [2,4,1,6]  ||  [2,4]', 'takewhile (<3) [1..5]   ||  [1,2]'],
    },
    {
        name: 'dropwhile',
        signature: 'dropwhile :: (* -> bool) -> [*] -> [*]',
        description: 'Descarta elementos del frente mientras el predicado se cumpla.',
        category: 'Listas',
        examples: ['dropwhile even [2,4,1,6]  ||  [1,6]'],
    },
    {
        name: 'zip2',
        signature: 'zip2 :: [*] -> [**] -> [(*,**)]',
        description:
            'Forma pares con los elementos en la misma posición; la longitud del resultado es la de la lista más corta (estilo habitual en Miranda).',
        category: 'Listas',
        examples: ['zip2 [0,1,2,3] "type"  ||  [(0,\'t\'),(1,\'y\'),(2,\'p\'),(3,\'e\')]'],
    },
    {
        name: 'zip',
        signature: 'zip :: ([*],[**]) -> [(*,**)]',
        description:
            'Versión Bird & Wadler: toma un **par** de listas (no currificada). Equivale a `zip2` aplicada a las dos listas.',
        category: 'Listas',
        examples: ['zip ([1,2,3],"abc")  ||  [(1,\'a\'),(2,\'b\'),(3,\'c\')]'],
    },
    {
        name: 'map2',
        signature: 'map2 :: (* -> ** -> ***) -> [*] -> [**] -> [***]',
        description:
            'Recorre dos listas en paralelo aplicando una función binaria (en Haskell suele llamarse `zipWith`).',
        category: 'Listas',
        examples: ['map2 (+) [1,2,3] [4,5,6]  ||  [5,7,9]'],
    },
    {
        name: 'zip3',
        signature: 'zip3 :: [*] -> [**] -> [***] -> [(*,**,***)]',
        description: 'Como `zip2` pero con tres listas y ternas.',
        category: 'Listas',
        examples: ['zip3 [1,2] "ab" [True,False]  ||  [(1,\'a\',True),(2,\'b\',False)]'],
    },
    {
        name: 'zip4',
        signature: 'zip4 :: [*] -> [**] -> [***] -> [****] -> [(*,**,***,****)]',
        description: 'Cuatro listas en paralelo → lista de 4-tuplas.',
        category: 'Listas',
    },
    {
        name: 'zip5',
        signature: 'zip5 :: [*] -> [**] -> [***] -> [****] -> [*****] -> [(*,**,***,****,*****)]',
        description: 'Cinco listas en paralelo → lista de 5-tuplas.',
        category: 'Listas',
    },
    {
        name: 'zip6',
        signature: 'zip6 :: [*] -> [**] -> [***] -> [****] -> [*****] -> [******] -> [(*,**,***,****,*****,******)]',
        description: 'Seis listas en paralelo → lista de 6-tuplas (no hay `zip7` en el stdenv).',
        category: 'Listas',
    },
    {
        name: 'transpose',
        signature: 'transpose :: [[*]] -> [[*]]',
        description: 'Traspone una matriz representada como lista de filas (maneja filas de distinta longitud).',
        category: 'Listas',
        examples: ['transpose [[1,2,3],[4,5,6]]  ||  [[1,4],[2,5],[3,6]]'],
    },
    {
        name: 'iterate',
        signature: 'iterate :: (* -> *) -> * -> [*]',
        description: 'Genera la lista infinita `[x, f x, f(f x), ...]`.',
        category: 'Listas',
        examples: ['take 5 (iterate (*2) 1)  ||  [1,2,4,8,16]'],
    },
    {
        name: 'repeat',
        signature: 'repeat :: * -> [*]',
        description: 'Genera la lista infinita con el valor repetido indefinidamente.',
        category: 'Listas',
        examples: ['take 4 (repeat 0)  ||  [0,0,0,0]'],
    },
    {
        name: 'rep',
        signature: 'rep :: num -> * -> [*]',
        description: 'Lista finita con `n` copias del mismo valor (replicar; `take n (repeat x)`).',
        category: 'Listas',
        examples: ['rep 6 \'o\'  ||  "oooooo"'],
    },
    {
        name: 'postfix',
        signature: 'postfix :: * -> [*] -> [*]',
        description: 'Añade un elemento al **final** de la lista (dual del constructor `:`).',
        category: 'Listas',
        examples: ['postfix 3 [1,2]  ||  [1,2,3]'],
    },
    {
        name: 'member',
        signature: 'member :: [*] -> * -> bool',
        description: 'Retorna `True` si el elemento pertenece a la lista.',
        category: 'Listas',
        examples: ['member [1,2,3] 2  ||  True', 'member [1,2,3] 5  ||  False'],
    },
    {
        name: 'index',
        signature: 'index :: [*] -> [num]',
        description:
            'Retorna la lista de índices válidos `[0 .. #x-1]` en orden creciente (p. ej. subscripts legales). No busca un elemento.',
        category: 'Listas',
        examples: ['index "hi"     ||  [0,1]', 'index "hippopotamus"  ||  [0..11]'],
    },
    {
        name: 'mkset',
        signature: 'mkset :: [*] -> [*]',
        description:
            'Elimina duplicados conservando el primer encuentro (lista como “conjunto”; en Haskell suele llamarse `nub`).',
        category: 'Listas',
        examples: ['mkset [1,2,1,3,2]  ||  [1,2,3]'],
    },
    {
        name: 'sort',
        signature: 'sort :: [*] -> [*]',
        description: 'Ordena la lista en orden ascendente.',
        category: 'Listas',
        examples: ['sort [3,1,4,1,5]  ||  [1,1,3,4,5]'],
    },
    {
        name: 'merge',
        signature: 'merge :: [*] -> [*] -> [*]',
        description: 'Combina dos listas ordenadas en una lista ordenada.',
        category: 'Listas',
        examples: ['merge [1,3,5] [2,4,6]  ||  [1,2,3,4,5,6]'],
    },
    {
        name: 'last',
        signature: 'last :: [*] -> *',
        description: 'Retorna el último elemento de una lista no vacía.',
        category: 'Listas',
        examples: ['last [1,2,3]  ||  3'],
    },
    {
        name: 'init',
        signature: 'init :: [*] -> [*]',
        description: 'Retorna todos los elementos excepto el último.',
        category: 'Listas',
        examples: ['init [1,2,3]  ||  [1,2]'],
    },
    {
        name: 'sum',
        signature: 'sum :: [num] -> num',
        description: 'Suma todos los elementos de la lista.',
        category: 'Listas',
        examples: ['sum [1,2,3,4]  ||  10'],
    },
    {
        name: 'product',
        signature: 'product :: [num] -> num',
        description: 'Multiplica todos los elementos de la lista.',
        category: 'Listas',
        examples: ['product [1,2,3,4]  ||  24'],
    },
    {
        name: 'max',
        signature: 'max :: [*] -> *',
        description: 'Mayor elemento de una lista no vacía según el orden `>`.',
        category: 'Listas',
        examples: ['max [1,2,12,-6,5]  ||  12', 'max "hippopotamus"  ||  \'u\''],
    },
    {
        name: 'min',
        signature: 'min :: [*] -> *',
        description: 'Menor elemento de una lista no vacía según el orden `<`.',
        category: 'Listas',
        examples: ['min [3,1,4,1,5]  ||  1'],
    },
    {
        name: 'and',
        signature: 'and :: [bool] -> bool',
        description: 'Retorna `True` si todos los elementos son `True`.',
        category: 'Listas',
        examples: ['and [True,True,True]   ||  True', 'and [True,False,True]  ||  False'],
    },
    {
        name: 'or',
        signature: 'or :: [bool] -> bool',
        description: 'Retorna `True` si al menos un elemento es `True`.',
        category: 'Listas',
        examples: ['or [False,True,False]  ||  True', 'or [False,False]       ||  False'],
    },
    // ── Aritmética ───────────────────────────────────────────────────────────
    {
        name: 'abs',
        signature: 'abs :: num -> num',
        description: 'Valor absoluto de un número.',
        category: 'Aritmética',
        examples: ['abs (-5)  ||  5', 'abs 3     ||  3'],
    },
    {
        name: 'max2',
        signature: 'max2 :: * -> * -> *',
        description: 'Mayor de dos valores según `>=` (el `max` de listas se define con `foldl1 max2`).',
        category: 'Aritmética',
        examples: ['max2 3 5  ||  5', 'max2 \'b\' \'a\'  ||  \'b\''],
    },
    {
        name: 'min2',
        signature: 'min2 :: * -> * -> *',
        description: 'Menor de dos valores según `<` (el `min` de listas usa `foldl1 min2`).',
        category: 'Aritmética',
        examples: ['min2 3 5  ||  3'],
    },
    {
        name: 'gcd',
        signature: 'gcd :: num -> num -> num',
        description: 'Máximo común divisor de dos enteros.',
        category: 'Aritmética',
        examples: ['gcd 12 8  ||  4', 'gcd 7 3   ||  1'],
    },
    {
        name: 'neg',
        signature: 'neg :: num -> num',
        description: 'Negación unaria (equivalente al prefijo `-`).',
        category: 'Aritmética',
        examples: ['neg 5  ||  -5'],
    },
    {
        name: 'subtract',
        signature: 'subtract :: num -> num -> num',
        description: '`subtract x y = y - x` (sección postfija de `-` no permitida en Miranda).',
        category: 'Aritmética',
        examples: ['subtract 3 10  ||  7'],
    },
    {
        name: 'lcm',
        signature: 'lcm :: num -> num -> num',
        description: 'Mínimo común múltiplo de dos enteros.',
        category: 'Aritmética',
        examples: ['lcm 4 6  ||  12'],
    },
    {
        name: 'even',
        signature: 'even :: num -> bool',
        description: 'Retorna `True` si el número es par.',
        category: 'Aritmética',
        examples: ['even 4  ||  True', 'even 3  ||  False'],
    },
    {
        name: 'odd',
        signature: 'odd :: num -> bool',
        description: 'Retorna `True` si el número es impar.',
        category: 'Aritmética',
        examples: ['odd 3  ||  True', 'odd 4  ||  False'],
    },
    {
        name: 'integer',
        signature: 'integer :: num -> bool',
        description: 'Retorna `True` si el número es un valor entero (sin parte fraccionaria).',
        category: 'Aritmética',
        examples: ['integer 3.0  ||  True', 'integer 3.5  ||  False'],
    },
    {
        name: 'entier',
        signature: 'entier :: num -> num',
        description: 'Retorna el piso (floor) de un número como entero.',
        category: 'Aritmética',
        examples: ['entier 3.7   ||  3', 'entier (-1.2)  ||  -2'],
    },
    {
        name: 'sqrt',
        signature: 'sqrt :: num -> num',
        description: 'Raíz cuadrada.',
        category: 'Aritmética',
        examples: ['sqrt 9.0   ||  3.0', 'sqrt 2.0   ||  1.4142...'],
    },
    {
        name: 'exp',
        signature: 'exp :: num -> num',
        description: 'Función exponencial e^x.',
        category: 'Aritmética',
        examples: ['exp 1  ||  2.71828...', 'exp 0  ||  1.0'],
    },
    {
        name: 'e',
        signature: 'e :: num',
        description: 'Base de los logaritmos naturales (`e = exp 1`).',
        category: 'Aritmética',
    },
    {
        name: 'log',
        signature: 'log :: num -> num',
        description: 'Logaritmo natural (base e).',
        category: 'Aritmética',
        examples: ['log 1.0      ||  0.0', 'log (exp 1)  ||  1.0'],
    },
    {
        name: 'log10',
        signature: 'log10 :: num -> num',
        description: 'Logaritmo en base 10.',
        category: 'Aritmética',
        examples: ['log10 100.0  ||  2.0', 'log10 1.0    ||  0.0'],
    },
    {
        name: 'sin',
        signature: 'sin :: num -> num',
        description: 'Seno (argumento en radianes).',
        category: 'Aritmética',
        examples: ['sin 0.0   ||  0.0', 'sin (pi/2)  ||  1.0'],
    },
    {
        name: 'cos',
        signature: 'cos :: num -> num',
        description: 'Coseno (argumento en radianes).',
        category: 'Aritmética',
        examples: ['cos 0.0  ||  1.0', 'cos pi   ||  -1.0'],
    },
    {
        name: 'tan',
        signature: 'tan :: num -> num',
        description: 'Tangente (argumento en radianes).',
        category: 'Aritmética',
        examples: ['tan 0.0     ||  0.0', 'tan (pi/4)  ||  1.0'],
    },
    {
        name: 'arctan',
        signature: 'arctan :: num -> num',
        description: 'Arcotangente; resultado en (-π/2, π/2). Ver también `sin`, `cos`.',
        category: 'Aritmética',
        examples: ['arctan 1.0  ||  0.7853... (π/4)', 'pi = 4*arctan 1'],
    },
    {
        name: 'pi',
        signature: 'pi :: num',
        description: 'La constante π ≈ 3.14159265...',
        category: 'Aritmética',
        examples: ['pi  ||  3.14159265...'],
    },
    {
        name: 'hugenum',
        signature: 'hugenum :: num',
        description: 'Mayor número fraccionario representable (orden ~1e308 en IEEE64).',
        category: 'Aritmética',
    },
    {
        name: 'tinynum',
        signature: 'tinynum :: num',
        description: 'Menor positivo distinto de cero representable como fraccionario.',
        category: 'Aritmética',
    },

    // ── Caracteres y cadenas ────────────────────────────────────────────────
    {
        name: 'code',
        signature: 'code :: char -> num',
        description: 'Retorna el código ASCII del carácter.',
        category: 'Caracteres',
        examples: ['code \'A\'  ||  65', 'code \'a\'  ||  97'],
    },
    {
        name: 'decode',
        signature: 'decode :: num -> char',
        description: 'Retorna el carácter correspondiente al código ASCII.',
        category: 'Caracteres',
        examples: ['decode 65  ||  \'A\'', 'decode 97  ||  \'a\''],
    },
    {
        name: 'digit',
        signature: 'digit :: char -> bool',
        description: 'Retorna `True` si el carácter es un dígito decimal.',
        category: 'Caracteres',
        examples: ['digit \'3\'  ||  True', 'digit \'a\'  ||  False'],
    },
    {
        name: 'letter',
        signature: 'letter :: char -> bool',
        description: 'Retorna `True` si el carácter es una letra.',
        category: 'Caracteres',
        examples: ['letter \'a\'  ||  True', 'letter \'1\'  ||  False'],
    },
    {
        name: 'spaces',
        signature: 'spaces :: num -> [char]',
        description: 'Genera una cadena de `n` espacios.',
        category: 'Caracteres',
        examples: ['spaces 3  ||  "   "'],
    },
    {
        name: 'lay',
        signature: 'lay :: [[char]] -> [char]',
        description: 'Concatena cadenas añadiendo `\\n` al final de cada una (formateo de salida; inverso de `lines` salvo un `\\n` final).',
        category: 'Caracteres',
        examples: ['lay ["hola","mundo"]  ||  "hola\\nmundo\\n"'],
    },
    {
        name: 'layn',
        signature: 'layn :: [[char]] -> [char]',
        description: 'Une una lista de cadenas numerando cada línea.',
        category: 'Caracteres',
        examples: ['layn ["a","b"]  ||  " 1) a\\n 2) b\\n"'],
    },
    {
        name: 'lines',
        signature: 'lines :: [char] -> [[char]]',
        description: 'Divide una cadena en una lista de líneas separadas por `\\n`.',
        category: 'Caracteres',
        examples: ['lines "a\\nb\\nc"  ||  ["a","b","c"]'],
    },
    {
        name: 'cjustify',
        signature: 'cjustify :: num -> [char] -> [char]',
        description: 'Centra la cadena en un campo de ancho `n` (relleno con espacios).',
        category: 'Caracteres',
        examples: ['cjustify 5 "hi"  ||  " hi "'],
    },
    {
        name: 'ljustify',
        signature: 'ljustify :: num -> [char] -> [char]',
        description: 'Alinea la cadena a la izquierda en un campo de ancho `n`.',
        category: 'Caracteres',
        examples: ['ljustify 5 "hi"  ||  "hi   "'],
    },
    {
        name: 'rjustify',
        signature: 'rjustify :: num -> [char] -> [char]',
        description: 'Alinea la cadena a la derecha en un campo de ancho `n` (usa `spaces`).',
        category: 'Caracteres',
        examples: ['rjustify 5 "hi"  ||  "   hi"'],
    },
    {
        name: 'numval',
        signature: 'numval :: [char] -> num',
        description: 'Convierte una cadena a su valor numérico.',
        category: 'Caracteres',
        examples: ['numval "42"    ||  42', 'numval "3.14"  ||  3.14'],
    },
    {
        name: 'shownum',
        signature: 'shownum :: num -> [char]',
        description: 'Convierte un número a su representación en cadena.',
        category: 'Caracteres',
        examples: ['shownum 42    ||  "42"', 'shownum 3.14  ||  "3.14"'],
    },
    {
        name: 'showfloat',
        signature: 'showfloat :: num -> num -> [char]',
        description: 'Primer argumento: decimales tras el punto; segundo: el número, en formato fijo.',
        category: 'Caracteres',
        examples: ['showfloat 2 3.14159  ||  "3.14"'],
    },
    {
        name: 'showscaled',
        signature: 'showscaled :: num -> num -> [char]',
        description: 'Notación científica; el `num` entero indica decimales en la mantisa.',
        category: 'Caracteres',
        examples: ['showscaled 2 1234.5  ||  cadena estilo "1.23e+03"'],
    },
    {
        name: 'show',
        signature: 'show :: * -> [char]',
        description:
            'En Miranda, `show` es una **palabra reservada** que denota una familia de conversiones a texto (según el tipo). `shownum` es el caso para `num`.',
        category: 'Caracteres',
        examples: ['show 42      ||  "42"', 'show [1,2,3]  ||  "[1,2,3]"'],
    },

    // ── Combinadores y orden superior ────────────────────────────────────────
    {
        name: 'id',
        signature: 'id :: * -> *',
        description: 'Función identidad: retorna su argumento sin modificarlo.',
        category: 'Combinadores',
        examples: ['id 42       ||  42', 'id "hello"  ||  "hello"'],
    },
    {
        name: 'const',
        signature: 'const :: * -> ** -> *',
        description: 'Retorna una función que ignora su argumento y siempre retorna el primer valor.',
        category: 'Combinadores',
        examples: ['const 5 "x"    ||  5', 'map (const 0) [1,2,3]  ||  [0,0,0]'],
    },
    {
        name: 'converse',
        signature: 'converse :: (* -> ** -> ***) -> ** -> * -> ***',
        description: 'Intercambia el orden de los dos primeros argumentos de una función binaria currificada.',
        category: 'Combinadores',
        examples: ['converse (-) 3 10  ||  7'],
    },
    {
        name: 'until',
        signature: 'until :: (* -> bool) -> (* -> *) -> * -> *',
        description: 'Aplica la función repetidamente hasta que el predicado sea `True`.',
        category: 'Combinadores',
        examples: ['until (>1000) (*2) 1  ||  1024'],
    },
    {
        name: 'limit',
        signature: 'limit :: [*] -> *',
        description: 'Primer valor de la lista igual a su sucesor (convergencia de sucesiones).',
        category: 'Combinadores',
        examples: ['limit [x | x <- 2, 0.5*(x + 2/x) .. ]  ||  raíz de 2'],
    },
    {
        name: 'seq',
        signature: 'seq :: * -> ** -> **',
        description: 'Evalúa el primer argumento hasta saber que no es totalmente indefinido y devuelve el segundo.',
        category: 'Combinadores',
    },
    {
        name: 'force',
        signature: 'force :: * -> *',
        description: 'Fuerza evaluación completa de una estructura finita antes de devolverla.',
        category: 'Combinadores',
        examples: ['hd (force x)'],
    },
    {
        name: 'undef',
        signature: 'undef :: *',
        description: 'Valor totalmente indefinido; cualquier uso provoca error.',
        category: 'Combinadores',
    },
    {
        name: 'error',
        signature: 'error :: [char] -> *',
        description: 'Termina el programa con el mensaje de error indicado.',
        category: 'Combinadores',
        examples: ['error "índice fuera de rango"'],
    },

    // ── Sistema e IO (UNIX) ─────────────────────────────────────────────────
    {
        name: 'read',
        signature: 'read :: [char] -> [char]',
        description: 'Lee el contenido del archivo dado por ruta; error si no existe o no hay permiso.',
        category: 'Sistema',
    },
    {
        name: 'filemode',
        signature: 'filemode :: [char] -> [char]',
        description: 'Permisos del archivo como cadena tipo `"drwx"` (carácter `-` si no aplica).',
        category: 'Sistema',
    },
    {
        name: 'getenv',
        signature: 'getenv :: [char] -> [char]',
        description: 'Consulta una variable de entorno por nombre.',
        category: 'Sistema',
        examples: ['getenv "HOME"'],
    },
    {
        name: 'system',
        signature: 'system :: [char] -> ([char],[char],num)',
        description: 'Ejecuta un comando shell; retorna salida estándar, salida de error y código de salida.',
        category: 'Sistema',
    },

    // ── Tuplas ───────────────────────────────────────────────────────────────
    {
        name: 'fst',
        signature: 'fst :: (*,**) -> *',
        description: 'Retorna el primer componente de un par.',
        category: 'Tuplas',
        examples: ['fst (1,2)    ||  1', 'fst ("a",3)  ||  "a"'],
    },
    {
        name: 'snd',
        signature: 'snd :: (*,**) -> **',
        description: 'Retorna el segundo componente de un par.',
        category: 'Tuplas',
        examples: ['snd (1,2)    ||  2', 'snd ("a",3)  ||  3'],
    },
];

export const preludeNames: string[] = prelude.map(e => e.name);

export function lookupEntry(name: string): PreludeEntry | undefined {
    return prelude.find(e => e.name === name);
}
